src/main/java/com/workshops/managing/system/model/MyUserPrincipal.java
package com.workshops.managing.system.model;

import com.workshops.managing.system.model.entity.Account;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class MyUserPrincipal implements UserDetails {

  private final String ROLE_PREFIX = "ROLE_";

  private Account account;

  public MyUserPrincipal(Account account) {
    this.account = account;
  }

  @Override
  public Collection<? extends GrantedAuthority> getAuthorities() {
    List<GrantedAuthority> authorities = new ArrayList<>();
    authorities.add(new SimpleGrantedAuthority(ROLE_PREFIX + account.getRole().getName()));
    return authorities;
  }

  @Override
  public String getPassword() {
    return account.getPassword();
  }

  @Override
  public String getUsername() {
    return account.getLogin();
  }

  @Override
  public boolean isAccountNonExpired() {
    return true;
  }

  @Override
  public boolean isAccountNonLocked() {
    return account.isActive();
  }

  @Override
  public boolean isCredentialsNonExpired() {
    return true;
  }

  @Override
  public boolean isEnabled() {
    return account.isEnabled();
  }
}

src/main/webapp/WEB-INF/jsp/403.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <style>
    i {
      ms-transform: translate(0, 20px);
      webkit-transform: translate(0, 20px);
      transform: translate(0,20px);
    }
  </style>
  <title>403</title>
</head>
<body class="cyan" ng-app="at">
<div class="container">
  <div class="row">
    <br>
    <br>
    <br>
    <div class="col s12 white z-depth-4" style="border-radius: 3px">
      <h2 class="center"><i class="material-icons large">lock_outline</i>403 {{'403.title' | translate}}</h2>
      <h4 class="center">{{'403.desc' | translate}}</h4>
    </div>
  </div>
</div>
<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/404.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <style>
    i {
      ms-transform: translate(0, 20px);
      webkit-transform: translate(0, 20px);
      transform: translate(0,20px);
    }
  </style>
  <title>404</title>
</head>
<body class="cyan" ng-app="at">
<div class="container">
  <div class="row">
    <br>
    <br>
    <br>
    <div class="col s12 white z-depth-4" style="border-radius: 3px">
      <h2 class="center"><i class="material-icons large">sentiment_dissatisfied</i>404 {{"404.title" | translate}}</h2>
      <h4 class="center">{{"404.desc" | translate}}</h4>
    </div>
  </div>
</div>
<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/500.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <style>
    i {
      ms-transform: translate(0, 20px);
      webkit-transform: translate(0, 20px);
      transform: translate(0,20px);
    }
  </style>
  <title>500</title>
</head>
<body class="cyan" ng-app="at">
<div class="container">
  <div class="row">
    <br>
    <br>
    <br>
    <div class="col s12 white z-depth-4" style="border-radius: 3px">
      <h2 class="center"><i class="material-icons large">sentiment_dissatisfied</i>500 {{"500.title" | translate}}</h2>
      <h4 class="center">{{"500.desc" | translate}}</h4>
      <h5 class="center">{{"accActivation.contact" | translate}}: workshops-managing-system@gmail.com</h5>
    </div>
  </div>
</div>
<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/editAccount.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
  <title>Edit account</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css?family=Quicksand:700" rel="stylesheet">
  <link rel="stylesheet" href="./../../css/style.css">
  <link rel="stylesheet" href="./../../css/spinner.css">

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body ng-app="app" ng-controller="editAccountController">

<div id="loader-wrapper">
  <div id="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>

<div id="spinner-wrapper">
  <div id="spinner"></div>
</div>

<header>
  <div ng-include="'/navigation'"></div>

  <nav class="white">
    <div class="nav-wrapper container">
      <div class="row">
        <div class="col s12">
          <a href="/" class="breadcrumb teal-text"><i class="material-icons">home</i></a>
          <a href="#!" class="breadcrumb teal-text">{{'common.accountEdition' | translate}}</a>
        </div>
      </div>
    </div>
  </nav>
</header>

<main>
  <input id="loginFromModel" ng-model="loginFromModel" value="${login}" type="hidden">

  <div class="container" style="margin-top: 50px">
    <div class="row">
      <form id="accountForm" name="accountForm" novalidate="novalidate">
        <div class="modal-content valign-wrapper">
          <div class="row">
            <div class="col s12 m12 l6 input-field input-margin">
              <i class="material-icons prefix">person_outline</i>
              <input id="login" type="text" name="login" ng-model="account.login" required aria-required="true"
                     minlength="4" disabled class="tooltipped" data-position="bottom" data-delay="50"
                     data-tooltip="Only ADMIN can change login.">
              <label for="login">{{'loginRegisterPage.username' | translate}}</label>
            </div>
            <div class="col s12 m12 l6 input-field input-margin">
              <i class="material-icons prefix">mail_outline</i>
              <input id="mail" type="email" name="email" ng-model="account.email" required aria-required="true">
              <label for="mail">Email</label>
            </div>
            <div class="col s12 m12 l6 input-field input-margin">
              <i class="material-icons prefix">border_color</i>
              <input id="firstName" type="text" name="firstName" ng-model="account.firstName" required
                     aria-required="true" minlength="2">
              <label for="firstName">{{'loginRegisterPage.firstName' | translate}}</label>
            </div>
            <div class="col s12 m12 l6 input-field input-margin">
              <i class="material-icons prefix">gesture</i>
              <input id="surname" type="text" name="surname" ng-model="account.surname" required
                     aria-required="true"
                     minlength="2">
              <label for="surname">{{'loginRegisterPage.surname' | translate}}</label>
            </div>
            <div class="col s12 m12 l6 input-field input-margin">
              <i class="material-icons prefix">lock_outline</i>
              <input id="password" type="password" name="password" ng-model="account.password" minlength="8">
              <label for="password">{{'loginRegisterPage.password' | translate}}</label>
            </div>
            <div class="col s12 m12 l6 input-field input-margin">
              <i class="material-icons prefix">lock_outline</i>
              <input id="passwordConfirm" type="password" name="passwordConfirm"
                     ng-model="account.passwordConfirm"
                     minlength="8">
              <label for="passwordConfirm">{{'loginRegisterPage.confirmPassword' | translate}}</label>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="row">
            <i class="col s12" style="color: grey">{{'common.emptyPasswd' | translate}}</i>
            <div class="col s12 right-align">
              <button id="submitBtn" class="btn waves-effect waves-light" type="submit" name="action">{{'common.submit'
                | translate}}
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</main>

<div ng-include="'/footer'" onload="onFooterLoad()"></div>

<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="./../../js/EndpointService.js"></script>
<script src="./../../dependencies/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.js"></script>
<script src="./../../js/editAccountController.js"></script>
<script src="./../../dependencies/slip.js"></script>
<script src="../../js/notificationsController.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
<script>
  jQuery.extend(jQuery.validator.messages, {
    equalTo: "Passwords do not match.",
  });

  jQuery.validator.addMethod("noSpace", function (value, element) {
    return value.indexOf(" ") < 0;
  }, "Whitespaces are not allowed.");
</script>
<c:if test="${pageContext.response.locale == 'pl'}">
  <script src="./../../dependencies/jquery.validate.messages_pl.js"></script>
</c:if>
<script>
  $(document).ready(function () {
    $.validator.setDefaults({
      errorClass: 'invalid',
      validClass: "valid",
      errorPlacement: function (error, element) {
        $(element)
          .closest("form")
          .find("label[for='" + element.attr("id") + "']")
          .attr('data-error', error.text());
      }
    });

    $("#accountForm").validate({
      rules: {
        password: {
          noSpace: true
        },
        passwordConfirm: {
          equalTo: "#password",
          noSpace: true
        },
        login: {
          noSpace: true
        },
        email: {
          noSpace: true
        }
      },
      submitHandler: function () {
        console.log('form ok');
        angular.element($('#submitBtn')).scope().submitBtnOnClick();
      }
    });
  });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/footer.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<footer class="page-footer cyan">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <span class="left">Praca inżynierska na kierunku Informatyka, wydział FTIMS Politechniki Łódzkiej.</span>
        <span class="right">Autor Dawid Dziedziczak 195576</span>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <span class="right">© 2017 All rights reserved.</span>
    </div>
  </div>
</footer>

src/main/webapp/WEB-INF/jsp/forgotPassword.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
  <title>Forgot password</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link rel="stylesheet" href="./../../css/style.css">
  <link rel="stylesheet" href="./../../css/spinner.css">
  <link rel="stylesheet" href="../../css/login-register-style.css">

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body ng-app="app" class="cyan" ng-controller="forgotPasswordController">
<div id="loader-wrapper">
  <div id="loader"></div>

  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>

</div>

<div id="spinner-wrapper">
  <div id="spinner"></div>
</div>

<div class="row">
  <div class="col s 12 z-depth-4 card-panel">
    <form id="resetPasswordForm" class="login-form" novalidate>
      <div class="row">
        <div class="col s12 center input-field">
          <img src="./../../icons-images/training_icon4.png" class="yellow responsive-img logo">
          <p class="center login-form-title">{{ 'logo1' | translate }} <br> {{ 'logo2' | translate }}</p>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">person_outline</i>
          <input id="login" type="text" name="login" ng-model="login" required aria-required="true" >
          <label for="login">{{ 'loginRegisterPage.username' | translate }}</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">mail_outline</i>
          <input id="email" type="email" name="email" ng-model="email" required aria-required="true" >
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 center input-field">
          <button id="submitBtn" class="btn col s12 waves-effect waves-light">
            {{ 'loginRegisterPage.resetPasswordBtn' | translate }}
          </button>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <p class="col s6 margin left-align medium-small">
            <a href="login">{{ 'loginRegisterPage.login' | translate }}</a>
          </p>
          <p class="col s6 margin right-align medium-small">
            <a href="register">{{ 'loginRegisterPage.register' | translate }}</a>
          </p>
        </div>
      </div>
    </form>
  </div>
</div>

<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="./../../js/EndpointService.js"></script>
<script src="./../../js/forgotPasswordController.js"></script>
<script src="./../../dependencies/jquery.validate.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
<script>
  jQuery.validator.addMethod("noSpace", function(value, element) {
    return value.indexOf(" ") < 0;
  }, "Whitespaces are not allowed.");
</script>
<c:if test="${pageContext.response.locale == 'pl'}">
  <script src="./../../dependencies/jquery.validate.messages_pl.js"></script>
</c:if>
<script>
  $.validator.setDefaults({
    errorClass: 'invalid',
    validClass: "valid",
    errorPlacement: function (error, element) {
      $(element)
        .closest("form")
        .find("label[for='" + element.attr("id") + "']")
        .attr('data-error', error.text())
        .parent().addClass("error-margin");
    },
    unhighlight: function(element, errorClass, validClass) {
      $(element).removeClass(errorClass).addClass(validClass).parent().removeClass("error-margin");
      $(element.form).find("label[for=" + element.id + "]")
        .removeClass(errorClass);
    },
    submitHandler: function (form) {
      angular.element($('#submitBtn')).scope().submitBtnOnClick();
    }
  });

  $("#resetPasswordForm").validate({
    rules: {
      login: {
        noSpace: true
      },
      email: {
        noSpace: true
      },
    }
  });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<html>
<head>
  <title>Title</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css?family=Quicksand:700" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.1.19/css/materialdesignicons.min.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link rel="stylesheet" href="./../../css/style.css">
  <link rel="stylesheet" href="./../../css/spinner.css">

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body ng-app="notificationsApp" ondragstart="return false;">

<div id="loader-wrapper">
  <div id="loader"></div>

  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>

</div>

<div id="spinner-wrapper">
  <div id="spinner"></div>
</div>

<div ng-include="'navigation'"></div>

<div class="parallax-container">
  <div class="parallax"><img src="./../../icons-images/event1.jpg"></div>
</div>
<div class="section white">
  <div class="row container page-description">
    <h2 class="header">{{'home.eventsManagingSystem' | translate }}</h2>
    <p class="grey-text text-darken-3 lighten-3">{{'home.description' | translate }}</p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><img src="./../../icons-images/event2.jpg"></div>
</div>

<div ng-include="'/footer'"></div>

<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="./../../dependencies/slip.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="./../../js/EndpointService.js"></script>
<script src="./../../js/common.js"></script>
<script src="../../js/notificationsController.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/invalidToken.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <title>Invalid token</title>
</head>
<body class="cyan" ng-app="at">
<div class="container">
  <div class="row">
    <br>
    <br>
    <br>
    <div class="col s12 white z-depth-4" style="border-radius: 3px">
      <i class="material-icons large">sentiment_dissatisfied</i><h2>{{ "accActivation.invalidToken" | translate}}</h2>
      <h4>{{ "accActivation.contact" | translate}}: workshops-managing-system@gmail.com</h4>
    </div>
  </div>
</div>
<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/register.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html>
<head>
  <title>Register</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link rel="stylesheet" href="./../../css/style.css">
  <link rel="stylesheet" href="./../../css/spinner.css">
  <link rel="stylesheet" href="../../css/login-register-style.css">

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body ng-app="app" class="cyan">
<div id="loader-wrapper">
  <div id="loader"></div>

  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>

</div>

<div id="spinner-wrapper">
  <div id="spinner"></div>
</div>

<div class="row" ng-controller="registerController">
  <div class="col s 12 z-depth-4 card-panel">
    <form id="registerForm" class="login-form" novalidate>
      <div class="row">
        <div class="col s12 center input-field">
          <img src="./../../icons-images/training_icon4.png" class="yellow responsive-img logo">
          <p class="center login-form-title">{{ 'logo1' | translate }} <br> {{ 'logo2' | translate }}</p>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">person_outline</i>
          <input id="login" type="text" name="login" ng-model="account.login" required aria-required="true" minlength="4">
          <label for="login">{{ 'loginRegisterPage.username' | translate }}</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">mail_outline</i>
          <input id="mail" type="email" name="email" ng-model="account.email" required aria-required="true">
          <label for="mail">Email</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">lock_outline</i>
          <input id="password" type="password" name="password" ng-model="account.password" required aria-required="true" minlength="8">
          <label for="password">{{ 'loginRegisterPage.password' | translate }}</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">lock_outline</i>
          <input id="passwordConfirm" type="password" name="passwordConfirm" ng-model="account.passwordConfirm" required aria-required="true" minlength="8">
          <label for="passwordConfirm">{{ 'loginRegisterPage.confirmPassword' | translate }}</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">border_color</i>
          <input id="firstName" type="text" name="firstName" ng-model="account.firstName" required aria-required="true" minlength="2">
          <label for="firstName">{{ 'loginRegisterPage.firstName' | translate }}</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 input-field">
          <i class="material-icons prefix">gesture</i>
          <input id="surname" type="text" name="surname" ng-model="account.surname" required aria-required="true" minlength="2">
          <label for="surname">{{ 'loginRegisterPage.surname' | translate }}</label>
        </div>
      </div>
      <div class="row margin">
        <div class="col s12 center input-field">
          <button id="registerBtn" class="btn col s12 waves-effect waves-light">
            {{ 'loginRegisterPage.registerNow' | translate }}
          </button>
        </div>
      </div>
      <div class="row">
        <div class="col s12 input-field">
          <p class="margin center-align medium-small">
            {{ 'loginRegisterPage.haveAnAccount' | translate }}<a href="login">{{ 'loginRegisterPage.login' | translate }}</a>
          </p>
        </div>
      </div>
    </form>
  </div>
</div>

<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="./../../js/EndpointService.js"></script>
<script src="./../../js/registerController.js"></script>
<script src="./../../dependencies/jquery.validate.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
<script>
  jQuery.validator.addMethod("noSpace", function(value, element) {
    return value.indexOf(" ") < 0;
  }, "Whitespaces are not allowed.");

  jQuery.extend(jQuery.validator.messages, {
    equalTo: "Passwords do not match.",
  });
</script>
<c:if test="${pageContext.response.locale == 'pl'}">
  <script src="./../../dependencies/jquery.validate.messages_pl.js"></script>
</c:if>
<script>
  $.validator.setDefaults({
    errorClass: 'invalid',
    validClass: "valid",
    errorPlacement: function (error, element) {
      $(element)
        .closest("form")
        .find("label[for='" + element.attr("id") + "']")
        .attr('data-error', error.text())
        .parent().addClass("error-margin");
    },
    unhighlight: function(element, errorClass, validClass) {
      $(element).removeClass(errorClass).addClass(validClass).parent().removeClass("error-margin");
      $(element.form).find("label[for=" + element.id + "]")
        .removeClass(errorClass);
    },
    submitHandler: function (form) {
      console.log('form ok');
      angular.element($('#registerBtn')).scope().registerBtnOnClick();
    }
  });


  $("#registerForm").validate({
    rules: {
      passwordConfirm: {
        noSpace: true,
        equalTo: "#password"
      },
      password: {
        noSpace: true
      },
      login: {
        noSpace: true
      },
      email: {
        noSpace: true
      }
    }
  });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/tokenExpired.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <title>Token expired</title>
</head>
<body class="cyan" ng-app="at">
<div class="container">
  <div class="row">
    <br>
    <br>
    <br>
    <div class="col s12 white z-depth-4" style="border-radius: 3px">
      <i class="material-icons large">sentiment_dissatisfied</i><h2>{{ 'accActivation.tokenExpired' | translate }}</h2>
      <h4><a href="/resendRegistrationToken?token=${param.token}">{{ 'accActivation.newEmail' | translate }}</a></h4>
      <h4>{{ 'accActivation.contact' | translate }}: workshops-managing-system@gmail.com</h4>
    </div>
  </div>
</div>
<script src="./../../dependencies/jquery-3.2.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script src="./../../dependencies/angular-translate.min.js"></script>
<script src="./../../js/translateProvider.js"></script>
</body>
</html>